# Generated by Django 5.1.7 on 2025-05-26 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_reservation_has_extra_voucher_and_more'),
        ('payments', '0005_alter_payment_reservation_alter_payment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentFailureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Amount in Rial (IRR)')),
                ('error_code', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('error_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Payment Failure Log',
                'verbose_name_plural': 'Payment Failure Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(help_text='Amount in Rial (IRR)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='authority',
            field=models.CharField(blank=True, db_index=True, help_text='Authority Code from ZarinPal', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ref_id',
            field=models.CharField(blank=True, db_index=True, help_text='Reference ID after success', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['authority', 'status'], name='payments_pa_authori_687a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['ref_id'], name='payments_pa_ref_id_87103e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'),
        ),
        migrations.AddField(
            model_name='paymentfailurelog',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='failure_logs', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentfailurelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_failures', to=settings.AUTH_USER_MODEL),
        ),
    ]
