# Generated by Django 5.1.7 on 2025-05-26 22:50

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_paymentfailurelog_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='failure_details',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Stores error details if payment failed', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='PaymentFailureLog',
        ),
    ]
