# Generated by Django 5.1.7 on 2025-05-21 21:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trust_score',
            field=models.IntegerField(default=0, help_text="User's trust score"),
        ),
        migrations.AddField(
            model_name='user',
            name='trust_score_recovery_days',
            field=models.IntegerField(default=0, help_text='Days until trust score recovers to zero if negative'),
        ),
        migrations.AddField(
            model_name='user',
            name='trust_score_updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
