# Generated by Django 5.1.7 on 2025-05-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_trust_score_user_trust_score_recovery_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='trust_score_recovery_days',
        ),
        migrations.AlterField(
            model_name='user',
            name='trust_score_updated_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the trust score was last updated'),
        ),
    ]
