# Generated by Django 5.1.7 on 2025-05-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Voucher discount amount', max_digits=10),
        ),
    ]
