# Generated by Django 5.1.7 on 2025-04-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='reservation',
            name='delivery_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_number',
            field=models.PositiveIntegerField(blank=True, help_text='Sequential number for each meal and day', null=True),
        ),
    ]
