# Generated by Django 5.1.7 on 2025-05-03 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_foodcategory_food_category'),
        ('menu', '0001_initial'),
        ('orders', '0003_remove_reservation_qr_code_reservation_delivery_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.food'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('pending_payment', 'Pending Payment'), ('waiting', 'Waiting'), ('preparing', 'Preparing'), ('ready_to_pickup', 'Ready to Pickup'), ('picked_up', 'Picked Up'), ('not_picked_up', 'Not Picked Up')], default='pending_payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.timeslot'),
        ),
    ]
