# Generated by Django 5.1.7 on 2025-05-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_reservation_food_alter_reservation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='delivery_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
