# Generated by Django 5.1.7 on 2025-05-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_reservation_delivery_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='has_extra_voucher',
            field=models.BooleanField(default=False, help_text='Whether this reservation uses an extra voucher'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price before any vouchers applied', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='trust_score_impact',
            field=models.IntegerField(default=0, help_text='Impact on user trust score from this reservation'),
        ),
    ]
