# Generated by Django 5.1.7 on 2025-05-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_foodcategory_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='supports_extra_voucher',
            field=models.BooleanField(default=False, help_text='Whether this food item supports extra vouchers'),
        ),
    ]
